In [ ]:
import numpy as np
import pandas as pd

In [ ]:
train = pd.read_csv('/content/Traindata.csv', header=None)
test = pd.read_csv('/content/Testdata.csv', header=None)

In [ ]:
train.head()

x1       x2       x3  y
0  0.55828  0.89844  0.14509  1
1  0.59887  0.42924  0.37727  1
2  0.14888  0.33433  0.27906  1
3  0.89971  0.59665  0.21390  1
4  0.45039  0.90199  0.13360  1

In [ ]:
train.columns = ['x1','x2', 'x3', 'y']
test.columns = ['x1','x2', 'x3', 'y']

In [ ]:
train['x4'] = (list(np.ones(len(train))))
test['x4'] = (list(np.ones(len(test))))

In [ ]:
train.head()

x1       x2       x3  y   x4
0  0.55828  0.89844  0.14509  1  1.0
1  0.59887  0.42924  0.37727  1  1.0
2  0.14888  0.33433  0.27906  1  1.0
3  0.89971  0.59665  0.21390  1  1.0
4  0.45039  0.90199  0.13360  1  1.0

In [ ]:
x_train = train[['x1','x2', 'x3', 'x4']]
y_train = train['y']

In [ ]:
x_test = test[['x1','x2', 'x3', 'x4']]
y_test = test['y']

In [ ]:
def pegasos(x_train,y_train, lamb=0.01, max_iter=1000):
    #T=1000
    #lamb = 0.01

    p = np.zeros(4)

    w_list = []
    for t in range(1,max_iter+1):
      if(t==1):
        w = np.zeros(4)
      else:
        w = (1/(lamb*(t-1)))*p
      i = np.random.randint(0,len(x_train))
      x = x_train.iloc[i]
      w_list.append(w)
      if(y_train[i]*np.dot(w,x) < 1):
        p+=y_train.iloc[i]*x
      #else:


    w_res = np.sum(np.array(w_list),axis=0)
    #w_normalized = w_res/sum(np.abs(w_res))

    #return w_normalized

    return w_res

In [ ]:
def get_accuracy(x_train, y_train, w):
  train_acc = 0

  for i in range(len(x_train)):
    pred = np.sign(np.dot(w, x_train.iloc[i]))
    if(pred == y_train.iloc[i]):
      train_acc+=1

    #else:
    #  print(i)

  return train_acc/len(x_train)

In [ ]:
w_result = pegasos(x_train, y_train, lamb = 0.01, max_iter=10000)

In [ ]:
get_accuracy(x_train,y_train)

In [ ]:
get_accuracy(x_test,y_test)

In [ ]:

lambda_list = [0.5, 0.3, 0.1, 0.05, 0.03, 0.01, 0.005]
for l in lambda_list:
  w_result = pegasos(x_train, y_train, lamb = l, max_iter=10000)
  train_accuracy = (get_accuracy(x_train,y_train))
  test_accuracy = get_accuracy(x_test,y_test)
  print("lambda = {} , train_acc = {}, test_acc = {}".format(l, train_accuracy, test_accuracy))

lambda = 0.5 , train_acc = 0.5, test_acc = 0.5
lambda = 0.3 , train_acc = 0.56, test_acc = 0.58
lambda = 0.1 , train_acc = 0.926, test_acc = 0.96
lambda = 0.05 , train_acc = 0.972, test_acc = 0.97
lambda = 0.03 , train_acc = 0.978, test_acc = 0.97
lambda = 0.01 , train_acc = 0.986, test_acc = 0.97
lambda = 0.005 , train_acc = 0.992, test_acc = 0.99


In [ ]:

lambda_list = [0.5, 0.3, 0.1, 0.05, 0.03, 0.01, 0.005, 0.003, 0.001]
for l in lambda_list:
  w_result = pegasos(x_train, y_train, lamb = l, max_iter=10000)
  train_accuracy = (get_accuracy(x_train,y_train, w_result))
  test_accuracy = get_accuracy(x_test,y_test,w_result)
  print("lambda = {} , train_acc = {}, test_acc = {}".format(l, train_accuracy, test_accuracy))

lambda = 0.5 , train_acc = 0.582, test_acc = 0.59
lambda = 0.3 , train_acc = 0.6, test_acc = 0.61
lambda = 0.1 , train_acc = 0.93, test_acc = 0.94
lambda = 0.05 , train_acc = 0.968, test_acc = 0.96
lambda = 0.03 , train_acc = 0.978, test_acc = 0.97
lambda = 0.01 , train_acc = 0.992, test_acc = 0.99
lambda = 0.005 , train_acc = 0.98, test_acc = 0.97
lambda = 0.003 , train_acc = 0.994, test_acc = 0.99
lambda = 0.001 , train_acc = 0.984, test_acc = 1.0


In [ ]:


best_test_acc = 0 
lambda_list = [0.5, 0.3, 0.1, 0.05, 0.03, 0.01, 0.005, 0.003, 0.001]
for l in lambda_list:
  w_result = pegasos(x_train, y_train, lamb = l, max_iter=10000)
  train_accuracy = (get_accuracy(x_train,y_train))
  test_accuracy = get_accuracy(x_test,y_test)

  if(test_accuracy> best_test_acc):
    best_test_acc = test_accuracy
    best_w = w_result
  print("lambda = {} , train_acc = {}, test_acc = {}".format(l, train_accuracy, test_accuracy))

lambda = 0.5 , train_acc = 0.5, test_acc = 0.5
lambda = 0.3 , train_acc = 0.594, test_acc = 0.61
lambda = 0.1 , train_acc = 0.9, test_acc = 0.93
lambda = 0.05 , train_acc = 0.97, test_acc = 0.97
lambda = 0.03 , train_acc = 0.976, test_acc = 0.97
lambda = 0.01 , train_acc = 0.99, test_acc = 0.98
lambda = 0.005 , train_acc = 0.994, test_acc = 0.99
lambda = 0.003 , train_acc = 0.978, test_acc = 0.97
lambda = 0.001 , train_acc = 0.996, test_acc = 1.0


In [ ]:
best_w

array([  -4126.89805775,    -545.31711777, -118700.12321658,
         59830.14931795])

In [ ]:


best_test_acc = 0 
lambda_list = [0.5, 0.3, 0.1, 0.05, 0.03, 0.01, 0.005, 0.003, 0.001]
for l in lambda_list:
  w_result = pegasos(x_train, y_train, lamb = l, max_iter=10000)
  train_accuracy = (get_accuracy(x_train,y_train,w_result))
  test_accuracy = get_accuracy(x_test,y_test,w_result)
  print(w_result)
  print(w_result/sum(np.abs(w_result)))

  if(test_accuracy> best_test_acc):
    best_test_acc = test_accuracy
    best_w = w_result
  print("lambda = {} , train_acc = {}, test_acc = {}".format(l, train_accuracy, test_accuracy))
print(best_w)

[ -315.3408473    -56.60698808 -5079.17070633   -76.20651976]
[-0.05705126 -0.0102413  -0.91892021 -0.01378723]
lambda = 0.5 , train_acc = 0.5, test_acc = 0.5
[ -327.2500033    211.04571972 -8208.58618677   304.2525317 ]
[-0.03615569  0.02331705 -0.90691241  0.03361485]
lambda = 0.3 , train_acc = 0.528, test_acc = 0.53
[  1603.18966901   2723.25687502 -19050.40489744   5891.58494573]
[ 0.05477538  0.09304415 -0.65088564  0.20129483]
lambda = 0.1 , train_acc = 0.924, test_acc = 0.95
[  1837.77520823   2538.747958   -25977.30788151  10312.02009021]
[ 0.0451921   0.06242948 -0.63879907  0.25357935]
lambda = 0.05 , train_acc = 0.968, test_acc = 0.97
[  1246.14431114   3064.35090539 -30684.26744671  12692.11697712]
[ 0.02613181  0.06425983 -0.64345304  0.26615533]
lambda = 0.03 , train_acc = 0.974, test_acc = 0.97
[    44.93399977   2734.75627718 -44391.90038091  20811.53368429]
[ 0.00066096  0.04022699 -0.65298412  0.30612794]
lambda = 0.01 , train_acc = 0.984, test_acc = 0.97
[  -133.2056

In [ ]:
for i in range(len(x_train)):
    pred = np.sign(np.dot(best_w, x_train.iloc[i]))
    print(pred)

In [ ]:
best_test_acc = 0 
lambda_list = [0.5, 0.3, 0.1, 0.05, 0.03, 0.01, 0.005, 0.003, 0.001]
for l in lambda_list:
  w_result = pegasos(x_train, y_train, lamb = l, max_iter=10000)
  train_accuracy = (get_accuracy(x_train,y_train,w_result))
  test_accuracy = get_accuracy(x_test,y_test,w_result)
  
  print(w_result)
  print(w_result/sum(np.abs(w_result)))
  train_accuracy1 = (get_accuracy(x_train,y_train,w_result/sum(np.abs(w_result))))
  test_accuracy1 = get_accuracy(x_test,y_test,w_result/sum(np.abs(w_result)))
  if(test_accuracy> best_test_acc):
    best_test_acc = test_accuracy
    best_w = w_result
  print("lambda = {} , train_acc = {}, test_acc = {}".format(l, train_accuracy, test_accuracy))
  print("lambda = {} , train_acc = {}, test_acc = {}".format(l, train_accuracy1, test_accuracy1))
print(best_w)

[ -231.23720273  -123.25269932 -5107.17149933  -297.05143926]
[-0.04015432 -0.02140282 -0.8868599  -0.05158296]
lambda = 0.5 , train_acc = 0.5, test_acc = 0.5
lambda = 0.5 , train_acc = 0.5, test_acc = 0.5
[ -367.96842557  -153.15565665 -8457.17987755  -152.14931243]
[-0.04030122 -0.01677416 -0.92626068 -0.01666394]
lambda = 0.3 , train_acc = 0.5, test_acc = 0.5
lambda = 0.3 , train_acc = 0.5, test_acc = 0.5
[  1357.51098102   2821.63832519 -18970.54837239   6171.84979246]
[ 0.04629739  0.09623088 -0.64698319  0.21048854]
lambda = 0.1 , train_acc = 0.946, test_acc = 0.95
lambda = 0.1 , train_acc = 0.946, test_acc = 0.95
[  1966.05792892   2437.92025839 -25812.31820602  10125.00910634]
[ 0.0487356   0.06043236 -0.63984836  0.25098367]
lambda = 0.05 , train_acc = 0.966, test_acc = 0.96
lambda = 0.05 , train_acc = 0.966, test_acc = 0.96
[  1305.84885692   2835.29420093 -30802.66391582  12930.65462706]
[ 0.02727652  0.05922352 -0.64340492  0.27009504]
lambda = 0.03 , train_acc = 0.976, tes

In [ ]:
best_w/sum(np.abs(best_w))

In [ ]:
np.dot(w_res, x_train.iloc[0])

In [ ]:
np.dot(w_res/sum(np.abs(w_res)), x_train.iloc[0])

In [ ]:
sum(np.abs(w_res))

In [ ]:
train_acc = 0


for i in range(len(x_train)):
  pred = np.sign(np.dot(w_result, x_train.iloc[i]))
  if(pred == y_train.iloc[i]):
    train_acc+=1

  else:
    print(i)

train_acc/len(x_train)

In [ ]:
len(test)

100

In [ ]:
test_acc = 0


for i in range(len(x_test)):
  pred = np.sign(np.dot(w_result, x_test.iloc[i]))
  if(pred == y_test.iloc[i]):
    test_acc+=1

  else:
    print(i)

test_acc/len(x_test)

1
63
85
92


0.96

In [ ]:
lst = [np.ones(3), np.ones(3)*0.5]
np.sum(np.array(lst),axis=0)


array([1.5, 1.5, 1.5])

In [ ]:
T=1000
lamb = 0.01

p = np.zeros(4)

w_list = []
for t in range(1,T+1):
  if(t==1):
    w = np.zeros(4)
  else:
    w = (1/(lamb*(t-1)))*p
  i = np.random.randint(0,len(x_train))
  x = x_train.iloc[i]
  w_list.append(w)
  if(y_train[i]*np.dot(w,x) < 1):
    p+=y_train.iloc[i]*x
  #else:


w_res = np.sum(np.array(w_list),axis=0)
w_normalized = w_res/sum(np.abs(w_res))

#return w_normalized

In [ ]:
len(w_list)

In [ ]:
w_result = w_normalized

In [ ]:
len(x_train)

500

In [ ]:
np.sign(-0.1)

-1.0

In [ ]:
w_normalized = w_res/sum(np.abs(w_res))

In [ ]:
np.dot(w_normalized, x_train.iloc[111])

0.006867396422408745

In [ ]:
train_acc = 0


for i in range(len(x_train)):
  pred = np.sign(np.dot(w_normalized, x_train.iloc[i]))
  if(pred == y_train.iloc[i]):
    train_acc+=1

  else:
    print(i)

train_acc/len(x_train)

12
30
36
70
217
443


0.988